on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        required: true
        description: 'Test scenario tags'
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - name: import python files
      uses: actions/setup-python@v2
      with:
        parameters_file: "test.py"
    - name: run
      run: |
        # echo "logLevel: ${{ github.event.inputs.logLevel }}"
        # echo "Tags: ${{ github.event.inputs.tags }}"
        python test.py
      shell: bash
