on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        required: true
        description: 'Test scenario tags'
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        # echo "logLevel: ${{ github.event.inputs.logLevel }}"
        # echo "Tags: ${{ github.event.inputs.tags }}"
        with open('123.txt','r') as f:
          f.write(${{ github.event.inputs.logLevel })
      shell: python
