on:
  workflow_dispatch:

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - with:
          path: .github/workflows/test.py
      - run: |
          python test.py
        shell: bash
