name: Code Change Pipeline CI

on:
  push:
    branches:
      - master
    #paths: 
    #   - '.github/workflows/train_model.yml' 
    #   - 'code/**' 

jobs:
  deployment:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v2

    # Connect the Azure Machine Learning Workspace
      - name: Connect Azure Machine Learning Workspace
        id: aml_workspace
        uses: Azure/aml-workspace@v1
        with:
            azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
