name: Huangluo Test

on:
  push:
    branches:
      - master
      - slave1
jobs:
  test_qa:
    if: ${{ github.ref == 'refs/heads/slave1' }}
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v2
      - run: echo "Test qa"

  deployment_test_prd:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v2
      - run: echo "Test prd"
